//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_platformer p_platformer;
        
        private static SteamVR_Input_ActionSet_buggy p_buggy;
        
        private static SteamVR_Input_ActionSet_mixedreality p_mixedreality;
        
        private static SteamVR_Input_ActionSet_Test_niput p_Test_niput;
        
        private static SteamVR_Input_ActionSet_farming p_farming;
        
        private static SteamVR_Input_ActionSet_UI_control p_UI_control;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_platformer platformer
        {
            get
            {
                return SteamVR_Actions.p_platformer.GetCopy<SteamVR_Input_ActionSet_platformer>();
            }
        }
        
        public static SteamVR_Input_ActionSet_buggy buggy
        {
            get
            {
                return SteamVR_Actions.p_buggy.GetCopy<SteamVR_Input_ActionSet_buggy>();
            }
        }
        
        public static SteamVR_Input_ActionSet_mixedreality mixedreality
        {
            get
            {
                return SteamVR_Actions.p_mixedreality.GetCopy<SteamVR_Input_ActionSet_mixedreality>();
            }
        }
        
        public static SteamVR_Input_ActionSet_Test_niput Test_niput
        {
            get
            {
                return SteamVR_Actions.p_Test_niput.GetCopy<SteamVR_Input_ActionSet_Test_niput>();
            }
        }
        
        public static SteamVR_Input_ActionSet_farming farming
        {
            get
            {
                return SteamVR_Actions.p_farming.GetCopy<SteamVR_Input_ActionSet_farming>();
            }
        }
        
        public static SteamVR_Input_ActionSet_UI_control UI_control
        {
            get
            {
                return SteamVR_Actions.p_UI_control.GetCopy<SteamVR_Input_ActionSet_UI_control>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_platformer = ((SteamVR_Input_ActionSet_platformer)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_platformer>("/actions/platformer")));
            SteamVR_Actions.p_buggy = ((SteamVR_Input_ActionSet_buggy)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_buggy>("/actions/buggy")));
            SteamVR_Actions.p_mixedreality = ((SteamVR_Input_ActionSet_mixedreality)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_mixedreality>("/actions/mixedreality")));
            SteamVR_Actions.p_Test_niput = ((SteamVR_Input_ActionSet_Test_niput)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Test_niput>("/actions/Test_niput")));
            SteamVR_Actions.p_farming = ((SteamVR_Input_ActionSet_farming)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_farming>("/actions/farming")));
            SteamVR_Actions.p_UI_control = ((SteamVR_Input_ActionSet_UI_control)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_UI_control>("/actions/UI_control")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.platformer,
                    SteamVR_Actions.buggy,
                    SteamVR_Actions.mixedreality,
                    SteamVR_Actions.Test_niput,
                    SteamVR_Actions.farming,
                    SteamVR_Actions.UI_control};
        }
    }
}
